---
title: "ASNZ membership map"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
    # pdf_document:
  html_document:
  # html_notebook:
    theme: spacelab
---

```{r setup, echo=FALSE}
# First load the town and suburb positions as saved by AIMSComponents.R
knitr::opts_chunk$set(echo=FALSE, cache=FALSE, error=TRUE)
load('townAndSuburbPositions')
# cairo_pdf()
```

```{r membersAddresses}
# Get addresses of members
addList <- gsheet::gsheet2tbl('https://docs.google.com/spreadsheets/d/117-hjbsw2lKb-ywtbMZV7Yqvw_eo1j9j8kk07WuxUgw/edit#gid=7')
addList <- as.data.frame(addList)[, c('Address2','Address3a','Region','Status')]
addList <- addList[tolower(addList$Status) %in% c('life member','member'),]
addList <- addList[!is.na(addList$Address2) | !is.na(addList$Address3a),]
addList[is.na(addList$Address3a), 'Address3a'] <- addList[is.na(addList$Address3a), 'Address2']
addList <- addList[addList$Region!='Overseas',]

# Identify central town for each region (this will need to be amended if members join from new regions)
regCent <- data.frame(Region=c('Auckland','Bay of Plenty','Canterbury','Christchurch','Coromandel','Dunedin','Hawkes Bay',
                               'Manawatu','Nelson/Marlborough','Northland','Otago','Taranaki','Waikato','Wellington','West Coast'),
                      Reo=c('Ta\u304maki-makau-rau','Te Moana-a-Toi','Waitaha','Waitaha','Hauraki','\u14ct\u101kou','Te Matau-a-M\u101ui',
                            'Manawat\u16b','Te Tau Ihu o Te Waka a M\u101ui','Te Tai Tokerau','\u14ct\u101kou','Taranaki','Waikato',
                            'Te Whanganui-a-Tara','Te Tai Poutini'),
                      Centre=c('Auckland','Tauranga','Christchurch','Christchurch','Thames','Dunedin','Napier',
                               'Palmerston North','Nelson','Whangarei','Dunedin','New Plymouth','Hamilton','Wellington','Greymouth'),
                      stringsAsFactors=FALSE)
addList <- merge(addList, regCent)

# Regional numbers
cexReg <- table(addList$Centre)
nosByReg <- data.frame(cex=cexReg, townPos[townPos$town %in% names(cexReg), -1])
nosByReg <- merge(regCent[!(regCent$Region %in% c('Christchurch','Dunedin')),], nosByReg, by.x='Centre', by.y='cex.Var1')
```

```{r theMap, fig.height=12, fig.cap='The area of the circle is proportional to the number of members in each region, and the circle is centred on the main city of the region.'}
par(xpd=TRUE, mar=rep(0,4))
myCol <- col2rgb('lightBlue')
maps::map('nz', fill=TRUE, col='lightGreen')
points(nosByReg[,'shape_X'], nosByReg[,'shape_Y'], pch=16, cex=sqrt(cexReg)/2,
       col=rgb(myCol[1], myCol[1], myCol[1], max=255, alpha=180))
points(nosByReg[,'shape_X'], nosByReg[,'shape_Y'], pch=1, cex=sqrt(cexReg)/2, col='darkBlue')
myAdj <- c(1,0,0,1,1,0,1,1,1,0,0,0,0) # this will need adjusting if new regions have been added above
myOff <- (1-2*myAdj)*0.22
for (i in 1:nrow(nosByReg))
{
  vOff <- 0.1
  text(nosByReg[i, 'shape_X']+myOff[i], nosByReg[i, 'shape_Y']+vOff,
       paste0(nosByReg[i, 'Region'], ' (', nosByReg[i, 'cex.Freq'], ')'),
       adj=myAdj[i], cex=0.9)
  text(nosByReg[i, 'shape_X']+myOff[i], nosByReg[i, 'shape_Y']-vOff, nosByReg[i, 'Reo'],
       adj=myAdj[i], cex=0.9)
  # text(nosByReg[i, 'shape_X']+myOff[i], nosByReg[i, 'shape_Y'],
  #      paste(nosByReg[i, 'Region'], nosByReg[i, 'Reo'], sep='\n'), adj=myAdj[i], cex=0.9)
}
```